apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logging
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra/base/logging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
    - name: monitoring  # Logging stack depends on monitoring for metrics
